name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.3

dependencies:
  dsql:
    path: ../
  faker: ^2.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
