name: dsql
description: Dart (PostgresSQL) SQL library for generating .dart files from .sql files and migrating the database based on the .sql files! Inspired by ORMs like Prisma (NodeJs) and SQLC (Golang).
version: 1.0.7
homepage: https://github.com/tihrasguinho/dsql
topics:
  - postgres
  - orm
  - prisma
  - sqlc

executables: 
  dsql: dsql

environment:
  sdk: ^3.0.0

license: MIT

dependencies:
  args: ^2.5.0
  path: ^1.8.3
  postgres: ^3.2.1
  strings: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
