name: dsql
description: Dart SQL library for generating .dart files from .sql files
version: 0.0.9+6
homepage: https://tihrasguinho.dev

executables: 
  dsql: dsql

environment:
  sdk: ^3.0.0

license: MIT

dependencies:
  args: ^2.4.2
  path: ^1.8.3
  postgres: ^2.6.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
