-- Entity => UserEntity 
CREATE TABLE IF NOT EXISTS tb_users (
  id VARCHAR(11) PRIMARY KEY NOT NULL DEFAULT id_generator(),
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  image VARCHAR(255),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  enabled BOOLEAN NOT NULL DEFAULT TRUE
);